<a href="https://colab.research.google.com/github/MostafaJahanian/DL_Projects/blob/main/PyTorch_Experimentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("This is an experimental notebook written merely for getting familiar with PyTorch")

This is an experimental notebook written merely for getting familiar with PyTorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
Matrix = torch.tensor([[7, 8],
                       [9 , 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
Matrix[0]

tensor([7, 8])

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [17]:
# Create a random tensor of size (3 ,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5907, 0.1446, 0.5926, 0.3527],
        [0.4173, 0.1219, 0.9561, 0.7235],
        [0.9230, 0.6618, 0.8502, 0.6138]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (3, 224, 224))

In [21]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensors and tensors-like

In [24]:
# Use torch.range() --> deprecated --> Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Create tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one the 3 common errors you'll run into with PyTorch and DL:
1. Tensors not right datatypes
3. Tensors not right shape
3. Tensors not on the right device

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # datatype of the tensor (eg. float32)
                               device = None, # the device tensor runs on (eg. cuda)
                               requires_grad = False) # whether or not track the gradient of the tensor
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [30]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. tensor.dtype
2. tensor.shape , tensor.ndim
3. tensor.device

In [32]:
# create a tensor
some_tensor = torch.rand(size = [3, 4])
some_tensor

tensor([[0.9781, 0.5774, 0.0833, 0.3250],
        [0.2882, 0.8977, 0.7395, 0.6227],
        [0.0496, 0.4558, 0.8506, 0.8810]])

In [33]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9781, 0.5774, 0.0833, 0.3250],
        [0.2882, 0.8977, 0.7395, 0.6227],
        [0.0496, 0.4558, 0.8506, 0.8810]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)
#### including:
1.Addition
2.Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Tryout PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
1. Element-wise multiplication
2. Matrix multiplication (dot product)
- The **inner dimensions** must match
- The result has the shape of **outer dimenstion**

In [39]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.5 ms, sys: 49 µs, total: 2.55 ms
Wall time: 2.2 ms


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 281 µs, sys: 23 µs, total: 304 µs
Wall time: 243 µs


tensor(14)

### One of the most common errors in deep learning is shape error

In [44]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#####To fix our tensor shape issues, we can manipulate the shape of one of our tensors using Transpose

In [47]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
print(torch.mm(tensor_A, tensor_B.T))
print(torch.matmul(tensor_A, tensor_B.T).shape, " Shape of the product of multiplication")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
torch.Size([3, 3])  Shape of the product of multiplication


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean - Note: the torch.mean() function requires a tensor of float32 dtype to function
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the positional min and max

In [60]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Find the POSITION of the min / max value in the tensor using argmin / argmax

In [62]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [63]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes a tensor to a defined shape
* View - return a view of a tensor but keep the same memory as the original tensor
* Stacking - adding tensors on top or aling each other
* Squeeze - remove all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a tensor
* Permute - return a view of the input with dimensions swapped in a certain way

In [64]:
# Create a tensor
x = torch.arange(1.0, 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
# add on extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
# Changing "z" changes "x" (cause a view shares the same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)   #also torch.vstack and torch.hstack
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
# torch.squeeze() - removes all single dimensions from a target tensors
print(f'Preveious tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Preveious tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [80]:
# add extra dimensions from x_unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')


New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [82]:
# torch.permute() - rearranges the dimensions of a tensor in a specific order
x_original = torch.rand(size = (224, 224, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0 -> 1   1 -> 2  2 -> 0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
