<a href="https://colab.research.google.com/github/MostafaJahanian/DL_Projects/blob/main/PyTorch_Experimentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("This is an experimental notebook written merely for getting familiar with PyTorch")

This is an experimental notebook written merely for getting familiar with PyTorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
Matrix = torch.tensor([[7, 8],
                       [9 , 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
Matrix[0]

tensor([7, 8])

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [17]:
# Create a random tensor of size (3 ,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9953, 0.1084, 0.5383, 0.3851],
        [0.9552, 0.1791, 0.4268, 0.6763],
        [0.8164, 0.5375, 0.6160, 0.8893]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (3, 224, 224))

In [21]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensors and tensors-like

In [24]:
# Use torch.range() --> deprecated --> Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Create tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one the 3 common errors you'll run into with PyTorch and DL:
1. Tensors not right datatypes
3. Tensors not right shape
3. Tensors not on the right device

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # datatype of the tensor (eg. float32)
                               device = None, # the device tensor runs on (eg. cuda)
                               requires_grad = False) # whether or not track the gradient of the tensor
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [33]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. tensor.dtype
2. tensor.shape , tensor.ndim
3. tensor.device

In [35]:
# create a tensor
some_tensor = torch.rand(size = [3, 4])
some_tensor

tensor([[0.9055, 0.8356, 0.2883, 0.6450],
        [0.8902, 0.8991, 0.3191, 0.3790],
        [0.3138, 0.7741, 0.3726, 0.2656]])

In [36]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9055, 0.8356, 0.2883, 0.6450],
        [0.8902, 0.8991, 0.3191, 0.3790],
        [0.3138, 0.7741, 0.3726, 0.2656]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)
#### including:
1.Addition
2.Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [45]:
# Tryout PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor, 10)

tensor([11, 12, 13])